server:
  port: 9003
spring:
  application:
    name: tensquare-qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.75.22.244:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true